server:
  port: 16001
spring:
  application:
    name: "consumer-service"
  cloud:
    loadbalancer:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
    #    可使用ip访问
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: "http://eurekaServer18000:18000/eureka/,http://eurekaServer18001:18001/eureka/,http://eurekaServer18002:18002/eureka/"
